### ISSUE TITLE
[suggestion] Attack jet

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#16]
**Issues:**
- Jet flying around cache and decache units quickly (regardless the sleep etc they do load the server)
- Jet has nothing to really attack, defenders have just few vehicles parked and they don't get reinforcements so the jet gonna move around without a real purpose (well it can kill SDK vehicle moving around)

**Suggestion:**
During a NATO vs CSAT (or vice versa) attack there are jets flying around and i'd suggest to make them have a single run and then RTB.

In case jets were intended to just to show, then remove the spawning trigger and make them dogfight (so jet with air-air combat) with defenders jets which takeoff (even from another airbase, why not)

**Comment by Barbolani77** [comment]
Solved
