### ISSUE TITLE
[suggestion] Attack - defensive infantry

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#17]
**Issue:**
- Some units manage to hide and they never get killed by attackers.
- "RANDOMUP" in a nice UPSMON feature but it still has some weird behaviour with certain buildings or buildings that should not be counted as such (example the pier)

**Suggestion:**
Is it possible to change the "fortify" behaviour after a certain time? So, it's ok they hide at the beginning, but then they have to join the fight at some point to let the dice roll.

**Comment by StefArma** [comment]
This is an evidence 
https://i.imgur.com/rbz8X5x.jpg

**Comment by Barbolani77** [comment]
or just dont add parameters?

**Comment by StefArma** [comment]
I tried it already, if the machine is slow they all spawn in same spot, and they need time to get away from it to avoid 1 HE kill them all.

**Comment by Barbolani77** [comment]
I think I will do some overhauling of UPSMon at this point.

On roadmap is a "zone under attack" detection. If a zone is being attacked, then we have to detect which units are fortified and just "free" them. Static units inside buildings are not a real addition.
