### ISSUE TITLE
[suggestion] move respawn from R key

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#21]
It's very common that you respawn unintentionally because you hit R to reload but at same time you take a bullet.

I'd suggest Spacebar as an alternative

**Comment by Barbolani77** [comment]
and then you have other user asking to remove the spacebar because they use it for whatever else :)

**Comment by StefArma** [comment]
well spacebar default keybind is actionmenu, R is reload. ofcourse someone can rebind however R is way more common than spacebar in fight.

Best would be long pressure key.. but it might be hard to code.. i'll check other mission if they a sort of
