### ISSUE TITLE
[Error] patrolReinf.sqf line 41

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#25]
*Version:* 0.11.2C

*Mods:* CBA, TFAR, Ace no medical

*Environment*:  MP dedi

*.rpt attatched?* line extracted below

*have you edited the missionfile?*: No

***Error:***
17:26:18 Error in expression <grupo) select count (wayPoints _grupo);				
_Vwp0 setWaypointType "GETOUT";	_grupo>				
17:26:18   Error position: <_Vwp0 setWaypointType "GETOUT";_grupo>				
17:26:18   Error Undefined variable in expression: _vwp0				
17:26:18 File mpmissions\__cur_mp.Tanoa\CREATE\patrolReinf.sqf, line 41

**Comment by Barbolani77** [comment]
Damm, lots of things to check :) tonight.

**Comment by StefArma** [comment]
4:02:17 Error in expression <grupo) select count (wayPoints _grupo); _Vwp0 setWaypointType "GETOUT"; _grupo>
     4:02:17   Error position: <_Vwp0 setWaypointType "GETOUT"; _grupo>
     4:02:17   Error Undefined variable in expression: _vwp0
     4:02:17 File mpmissions\__cur_mp.Tanoa\CREATE\patrolReinf.sqf, line 41

appearing in 0.11.3 too

**Comment by Barbolani77** [comment]
Fuck, I forgot to correct that.

Not a showstopper, the area will simply not get reinforced.

**Comment by Barbolani77** [comment]
Replace this:

_Vwp0 = (wayPoints _grupo) select count (wayPoints _grupo);

By this:

_Vwp0 = (wayPoints _grupo) select (count (wayPoints _grupo) - 1);

**Comment by StefArma** [comment]
copy!

**Comment by StefArma** [comment]
Fixed 0.11.3B https://github.com/A3Antistasi/Antistasi-WotP/commit/ee94228f2607e8914ae3f51dc552d73f616d332c
