### ISSUE TITLE
[Error] attaqueAAF & killZones

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#27]
*Version:* 0.11.2

*Mods:* CBA, TFAR Ace Nomedical

*Environment*: MP dedi.

*.rpt attatched?* exctracted below

*have you edited the missionfile?*: No

      9:14:17 Error in expression <) then {_times = _times * 4}; if (_x in _killZones) then { _sitio = _x; _times =>
      9:14:17   Error position: <_killZones) then { _sitio = _x; _times =>
      9:14:17   Error Undefined variable in expression: _killzones
      9:14:17 File mpmissions\__cur_mp.Tanoa\ataqueAAF.sqf, line 203

repeated a lot of times

**Comment by Barbolani77** [comment]
For unkown reasons killzones got corrupted. I will investigate tonight.
