### ISSUE TITLE
[Error] reinforcementsAI.sqf 

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#29]
*Version:* 0.11.2

*Mods:* CBA, TFAR Ace no medical

*Environment*: MP dedi.

*.rpt attatched?* highlight below

*have you edited the missionfile?*: No

     10:27:11 Error in expression <= getMarkerPos _aeropuerto; _posibles = _posibles select {((getMarkerPos _x dist>
     10:27:11   Error position: <_posibles select {((getMarkerPos _x dist>
     10:27:11   Error Undefined variable in expression: _posibles
     10:27:11 File mpmissions\__cur_mp.Tanoa\CREATE\reinforcementsAI.sqf, line 28

---

     10:27:11 Error in expression <= getMarkerPos _aeropuerto; _posibles = _posibles select {((getMarkerPos _x dist>
     10:27:11   Error position: <_posibles select {((getMarkerPos _x dist>
     10:27:11   Error Undefined variable in expression: _posibles
     10:27:11 File mpmissions\__cur_mp.Tanoa\CREATE\reinforcementsAI.sqf, line 28

**Comment by Barbolani77** [comment]
Related to killzones bug.

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/Antistasi-WotP/issues/27  referenced
