### ISSUE TITLE
[bug] CSAT default airport with NATO garrison

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#30]
*Version:* 0.11.2

*Mods:* CBA, TFAR, Ace no medical

*Environment*: MP dedi.

*.rpt attatched?* Nothing about it

*have you edited the missionfile?*: No

***Issue:***
As screenshot show in MP late campaign this is happening, have to check and try to reproduce SP when campaign starts.

Screenshot: https://imgur.com/wz6O4nj

EDIT: 
Not happening in SP with a new campaign.
Gonna check if airport_1 is in mrkCSAT on the server

**Comment by StefArma** [comment]
There are many markers not corresponding

"airport" in mrknato return true but it's CSAT on map

**Comment by Barbolani77** [comment]
Will check it. Anyway, the old array system has been removed, and what the engine uses is lados getVariable "airport"
