### ISSUE TITLE
[Error] miembros in MP LAN

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#31]
*Version:* 0.11.2

*Mods:* CBA, TFAR, ACE no medical

*Environment*: MP LAN

*.rpt attatched?* highlighted below 

*have you edited the missionfile?*: No

     18:30:56 File C:\Users\Stef\Documents\Arma 3\missions\WotP.Tanoa\orgPlayers\mList.sqf, line 4
     18:30:56 Error in expression <ist.sqf"if !(isServer) exitWith {};{ miembros pushBackUnique _x;} forEach [ >
     18:30:56   Error position: <miembros pushBackUnique _x; } forEach [ >
     18:30:56   Error Undefined variable in expression: miembros
     18:30:56 File C:\Users\Stef\Documents\Arma 3\missions\WotP.Tanoa\orgPlayers\mList.sqf, line 4

Started happening after https://github.com/A3Antistasi/Antistasi-WotP/commit/78db9c4eaa181e36b0fb07a7c37709668b835615

Quick/temporary fix:  
- globalexec
     
      miembros = ["yoursteam64xid"];
- Persistent save
- abort, start mission again and it's all fixed

**Comment by Barbolani77** [comment]
This is probably related to the servidoresOficiales removal, I will check it and at least bulletproof mlist in case the variable has not been set yet,

**Comment by Barbolani77** [comment]
Fuck we are adding the official members to any community!

I will revert all the servidoresoficiales thing, except the autosave, which will be added to everybody.

**Comment by StefArma** [comment]
i need to try again adding the memberlist.txt file reading from server. failed twice so far

**Comment by Barbolani77** [comment]
Thats another story
