### ISSUE TITLE
[Error] UPS artillery

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#32]
*Version:* 0.11.2

*Mods:* CBA, TFAR, ACE No medical

*Environment*: MP dedi.

*.rpt attatched?* highlight below

*have you edited the missionfile?*: No

     11:31:59 Error in expression <_Battery",[]])select 0;_batteryunits = _staticteam;{If (alive _x && vehicle _>
     11:31:59   Error position: <_staticteam;{If (alive _x && vehicle _>
     11:31:59   Error Undefined variable in expression: _staticteam
     11:31:59 File mpmissions\__cur_mp.Tanoa\Scripts\UPSMON\MODULES\ARTILLERY\fnc\UPSMON_artillerysetBattery.sqf, line 54

unknown moment, just found on .rpt

**Comment by Barbolani77** [comment]
90% chance its caused because of despawned mortar team while the script was running. UPSMon errors may appear sometimes, but as long they are not recurrent, I don't mess with them.
