### ISSUE TITLE
[Error] Convoy.sqf and taskupdate.sqf

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#33]
*Version:* 0.11.2

*Mods:* CBA, TFAR, Ace no Medical

*Environment*: MP dedi.

*.rpt attatched?* highlight below

*have you edited the missionfile?*: No

Out of context,  found in .rpt 

     12:09:31 Error in expression <l BIS_fnc_taskDestination; if (typeName _destino != typeName _destinoOld) then {
     12:09:31   Error position: <_destino != typeName _destinoOld) then {
     12:09:31   Error Undefined variable in expression: _destino
     12:09:31 File mpmissions\__cur_mp.Tanoa\Missions\taskUpdate.sqf, line 14

----
      12:09:31 Error in expression <chalimnum] select 4],"Contact Informer",_ciudad],position _casa,"FAILED"] call t
     12:09:31   Error position: <_ciudad],position _casa,"FAILED"] call t
     12:09:31   Error Undefined variable in expression: _ciudad
     12:09:31 File mpmissions\__cur_mp.Tanoa\Missions\CONVOY.sqf, line 82

**Comment by Barbolani77** [comment]
Noted,. Irrelevant in any case as the line refers to a situation on which there is no mission.
