### ISSUE TITLE
[Error] arsenalManage.sqf

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#34]
*Version:* 0.11.2

*Mods:* CBA, TFAR Ace No medical

*Environment*: , MP dedi.

*.rpt attatched?* highlight below

*have you edited the missionfile?*: No

Without context

     13:41:24 Error in expression <getText (configFile >> "CfgVehicles" >> _lockedMochi >> "displayName")]; unlocke>
     13:41:24   Error position: <_lockedMochi >> "displayName")]; unlocke>
     13:41:24   Error Undefined variable in expression: _lockedmochi
     13:41:24 File mpmissions\__cur_mp.Tanoa\Municion\arsenalManage.sqf, line 90

**Comment by Barbolani77** [comment]
Solved in the next patch :)
