### ISSUE TITLE
[Error] 0.11.3 missionrequest.sqf line 86

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#36]
*Version:* 0.11.3.

*Mods:* CBA, TFAR, Ace no medical

*Environment*: MP dedi.

*.rpt attatched?* highlighted below

*have you edited the missionfile?*: Yes https://github.com/A3Antistasi/Antistasi-WotP/pull/22

Informant is there, but i can't talk after a teleport in

    19:44:25 Error in expression <ntenas;_sitios = _sitios select {lados getVariable [_x,sideUnknown] != buenos};>
    19:44:25   Error position: <getVariable [_x,sideUnknown] != buenos};>
    19:44:25   Error Type Object, expected String
    19:44:25 File mpmissions\__cur_mp.Tanoa\Missions\missionrequest.sqf, line 86

**Comment by StefArma** [comment]
aeropuertos + antenas select {lados getVariable [_x,sideUnknown] != buenos}

i tried from console: return correctly values ["airport","airport_1","airport_3","airport_4"]

**Comment by Barbolani77** [comment]
Hi! This is because antenas is an array of objects and not markers.

If you update the gith code with a depbo of the steam mission I will be able to provide a fix.

**Comment by Barbolani77** [comment]
Ok got it from your pull request.

As easy as replacing this:

_sitios = aeropuertos + antenas; 
_sitios = _sitios select {lados getVariable [_x,sideUnknown] != buenos};

by this:

_sitios = aeropuertos select {lados getVariable [_x,sideUnknown] != buenos};
_sitios = _sitios + antenas;

**Comment by StefArma** [comment]
Fixed 0.11.3B https://github.com/A3Antistasi/Antistasi-WotP/commit/ee94228f2607e8914ae3f51dc552d73f616d332c
