### ISSUE TITLE
[suggestion] Dynamic reward AI joining

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#38]
Considered:
AI usage in WotP is fun and necessary, and there are situations like joining town and surrender.. it could be a player choice to accept AI joining on the fight or send them back to HQ

**Suggestion**
- Supply Delivery: random group leader nearby get a random number of AI (~3) on completion
basically civilians are thanksful and wish to join

- Surrender: in case he join, he can become part of your squad instantly with his gears or go to HQ and become +1 HR.

This system will solve situation at beginning of the game where HR are low, make enemies surrender and increase your fireteam.

**Comment by Barbolani77** [comment]
You havent fought CSAT too much, do you? :)
