### ISSUE TITLE
[error] garrisonUpdate.sqf

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#40]
*Version:* 0.12.0A

*Mods:* CBA, TFAR, Ace no Medical

*Environment*: MP dedi.

*.rpt attatched?* YES highlighted below

*have you edited the missionfile?*: No

    11:29:25 Error in expression <ado == malos) and (!(lados getVariable [_marcador,sideUnknown] == malos))) exitW>
    11:29:25   Error position: <_marcador,sideUnknown] == malos))) exitW>
    11:29:25   Error Undefined variable in expression: _marcador
    11:29:25 File mpmissions\__cur_mp.Tanoa\CREATE\garrisonUpdate.sqf, line 21

---

    11:29:25 Error in expression <) then {_garrison pushBack _tipo} else {_garrison append _tipo}; };garrison set>
    11:29:25   Error position: <_garrison append _tipo}; }; garrison set>
    11:29:25   Error Undefined variable in expression: _garrison
    11:29:25 File mpmissions\__cur_mp.Tanoa\CREATE\garrisonUpdate.sqf, line 34

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/Antistasi-WotP/pull/43/commits/58150399085ce51809c2b3d9233177932c30c14f

**Comment by Barbolani77** [comment]
I placed a debug on that script, check if you find something in the previous lines.

**Comment by Barbolani77** [comment]
this: Antistasi: Error en garrisonUpdate al enviar mal datos

**Comment by StefArma** [comment]
no "Error en garrisonUpdate al enviar mal datos" so far, nor .sqf lines reporting error too

**Comment by StefArma** [comment]
tonight event, we'll see

**Comment by Barbolani77** [comment]
Stinks to last unit of a roadblock killed

**Comment by StefArma** [comment]
Yes, look this report was from version 0.12.0A, we're on 0.12.1... event done, and nothing showed on .rpt   actually... i can't see any ANTISTASI diag_log apart the init ones, but no attack, or qrf etc. and we had plenty of...

**Comment by Barbolani77** [comment]
My friend: you are used to a disfunctional HC management on which the QRFs were done by the server and the HCs were idle because of unproper testing. Once we have been able to check if HCs have AI load or not, the thing has been coded properly.

And when HCs manage a qrf, the diag_log message is done...in the HC :)

**Comment by StefArma** [comment]
i imagined so
