### ISSUE TITLE
[issue] AI Limiter and Attack

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#45]
*Version:* 1.0.rc1
*Mods:* CBA, TFAR
*Environment*: SP
*.rpt attatched?* Not relevant
*have you edited the missionfile?*: No

***Issue:***
I'm in a dense populated area, NATO attack spawn but because of AI limiter set to 140, 4 trucks departed without units on them.

Would it be possible to just delay the attack once the AI counter get lower?

**Comment by Barbolani77** [comment]
It is, will do.

Also what I can do is to add additional waves in case the final number of soldiers spawned in one is like this.

**Comment by Barbolani77** [comment]
lets say if (count _soldados < 25) then {_waves = _waves + 1}, so yes, 4 soldiers reached, but sooner or later, when the map is more clear, the real attack will come.

**Comment by Barbolani77** [comment]
Done
