### ISSUE TITLE
[minor issue] surrendered wander around 

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#51]
*Version:* 1.0.0.rc3

*Mods:* CBA, TFAR, ACE(no-medical)

*Environment*: SP

*.rpt attatched?* no

*have you edited the missionfile?*: No

***Issue:***

Surrendered units start wandering around after some time, they should go to HQ but they just roam
I won't exclude ACE interference

**Comment by Barbolani77** [comment]
You mean without interrogate / free them?

**Comment by StefArma** [comment]
Free

**Comment by Barbolani77** [comment]
Intended, will check if I gave them destination.

**Comment by Barbolani77** [comment]
Reviewed, they work that way, closing
