### ISSUE TITLE
Disable Apex/Marksmen Weapons/Stuffs

### ISSUE THREAD

**Issue by gallexme** [A3Antistasi/Antistasi-WotP#55]
Hey,
Many of my friends aint got the DLCS, so they cant use any default unlocked  weapons apart form one arsenal weapon, 
Also they cant use the 4wd Offroader

and like 50% of the loot is marksmen/apex loot :(
we added the FFAA mod so there is some variety, but i would like to disable all of them

**Comment by zalexki** [comment]
Last known situation is that Antistasi will be polished for 0 DLC required.

**Comment by Barbolani77** [comment]
changed those loadouts on next patch. Not 100% vanilla but workable. Thanks!
