### ISSUE TITLE
cuentaca with negative value

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#6]
https://github.com/A3Antistasi/Antistasi-WotP/blob/fcdce1f18ca3b79f13475e8c9c8be8cb0d597d2e/resourcecheck.sqf#L162

Is the == a mistake? 
For some reason cuentaca get negative

**Comment by Barbolani77** [comment]
Fuck, that is not a mistake, but yes fot two lines below. Thats a showstopper. Going to publish release with everything

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/Antistasi-WotP/commit/1ff3fd219ed18267ce1d744f13d2a8a37863cd8e Barbolani solved

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/Antistasi-WotP/commit/6d545ec6645de122057d37195769c832f2f889dc done
