### ISSUE TITLE
How do you hack UAV's?

### ISSUE THREAD

**Issue by gallexme** [A3Antistasi/Antistasi-WotP#60]
Hey,
so ive got a Darter drone [NATO]
how can i change its faction to mine

according to changelog:
 Officer players can now hack UAVs.
i dont see any option neither in code, nor ingame ?

**Comment by StefArma** [comment]
please don't use github for such questions, there is forum for it. we use git for technical reporting

**Comment by gallexme** [comment]
would still be nice to know where its in the code?

**Comment by Barbolani77** [comment]
unitTrait command
